YOMDB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls'),)
]

movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.search_movies, name='search_movies'),
    path(
        'watchlist/add/<str:movie_id>/', views.toggle_movie_to_watchlist, 
        name='toggle_movie_to_watchlist'
        ),
    path(
        'watchlist/update/<str:movie_id>/', views.update_watchlist_item, 
        name='update_watchlist_item'
        ),
    path('watchlist/', views.WatchListView.as_view(), name='WatchListView')
]

movies/models.py
from django.db import models

from django.contrib.auth.models import User


class WatchList(models.Model):
    movie_title = models.CharField(max_length=100)
    movie_id = models.CharField(max_length=9, db_index=True)
    movie_genre = models.CharField(max_length=255)
    movie_actors = models.CharField(max_length=1000)
    movie_poster = models.URLField(blank=True)
    user = models.ForeignKey(User, related_name='watchlist', on_delete=models.CASCADE)
    watched = models.BooleanField(default=False)
    added = models.DateField(auto_now_add=True,)

    def __str__(self):
        return f'{self.user} wants to watch {self.movie_title}'

    class Meta:
        ordering = ['-added']
        unique_together = ['movie_id', 'user']

movies/forms.py
from django import forms

class SearchMoviesForm(forms.Form):
    title = forms.CharField(
        max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Movie title', 'label': ''})
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['title'].label = ''

movies/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import JsonResponse
from django.views.generic import ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from django.db.models import Q

import requests

from .forms import SearchMoviesForm
from .models import WatchList


def search_movies(request):
    form = SearchMoviesForm(request.GET or None)
    context = {
        'form': form
    }
    page_number = request.GET.get('page', 1)

    if request.method == "GET":
        if form.is_valid():
            movies = requests.get(
                f"http://www.omdbapi.com/?s={form.cleaned_data['title']}&page={page_number}&apikey={settings.OMDB_API_KEY}"
                )
            
            context['movies'] = movies.json().get('Search', False)
            context['max_page'] = range(1, round(int(movies.json().get('totalResults', 0)) / 10 + 1))

    return render(request, 'movies/search.html', context)


def toggle_movie_to_watchlist(request, movie_id):
    user = request.user
    resp = {}
    if request.method == 'POST':
        if not user.is_authenticated:
            return JsonResponse({'error': 'Login'}, status='400')

        movie = requests.get(
                    f"http://www.omdbapi.com/?i={movie_id}&apikey={settings.OMDB_API_KEY}"
                    ).json()

        if WatchList.objects.filter(user=user, movie_id=movie_id).exists():
            WatchList.objects.filter(user=user, movie_id=movie_id).delete()
            resp['removed'] = True

        else:
            resp['removed'] = False
            watch = WatchList()
            watch.movie_title = movie['Title']
            watch.movie_actors = movie['Actors']
            watch.movie_genre = movie['Genre']
            watch.movie_poster = movie['Poster']
            watch.user = user
            watch.movie_id = movie_id

            watch.save()
    return JsonResponse(resp)


class WatchListView(LoginRequiredMixin, ListView):
    model = WatchList
    template_name = 'movies/user_watchlist.html'


    def get_queryset(self):
        watched = self.request.GET.get('watched')
        actor = self.request.GET.get('actor')
        genre = self.request.GET.get('genre')
        filter_watchlist = Q()
        if watched:
            filter_watchlist &= Q(watched=watched)
        if actor:
            filter_watchlist &= Q(movie_actors__icontains=actor)
        if genre:
            filter_watchlist &= Q(movie_genre__icontains=genre)
        return self.model.objects.filter(user=self.request.user).filter(filter_watchlist)


@require_http_methods(['POST'])
def update_watchlist_item(request, movie_id):
    if request.method == "POST":
        watched = request.POST.get('watched')
        if watched == 'True':
            code = messages.success
            message = 'Movie set to watched successfully'
        else:
            code = messages.error
            message = "Movie set to not watched successfully"
        WatchList.objects.filter(user=request.user, movie_id=movie_id).update(watched=watched)
        code(request, message)
    return redirect('movies:WatchListView')

templates/base.html
<!DOCTYPE html>{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://kit.fontawesome.com/1ba3264fe7.js" crossorigin="anonymous"></script>
	{% block style %}{% endblock style %}
</head>
<body>
	{% include 'partials/_navbar.html' %}
    {% block content %}
	{% endblock content %}
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
	<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
	{% block scripts %}{% endblock scripts %}
</body>
</html>

templates/movies/search.html
{% extends 'base.html' %}
{% load crispy_forms_tags static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'movies/css/style.css' %}">
{% endblock style %}

{% block content %}
<div class="container my-3">
    <form class="mb-3" method="get">
        {{ form|crispy }}
    <input type="submit" value="Search" class="btn btn-primary btn-block">
    </form>
    {% if movies %}
    <div id="grid">
        {% for movie in movies %}
            <div class="grid-sizer"></div>
            <!-- Card -->
            <div class="grid-item">
                {% include 'partials/_card.html' %}
            </div>
        {% endfor %}

    </div>
    {% include 'partials/_pagination.html' %}

    {% else %}
    {% if request.GET.title %}
    <p>No movies for <strong>{{ request.GET.title }}.</strong></p>
    {% else %}
    <p>Search by name of movie in searchbox.</p>
    {% endif %}
    {% endif %}

</div>

{% endblock content %}

{% block scripts %}
    <script src="{% static 'movies/js/movies.js' %}"></script>
{% endblock scripts %}

templates/movies/user_watchlist.html
{% extends 'base.html' %}
{% load crispy_forms_tags static %}

{% block content %}
{% include 'partials/_alerts.html' %}
<div class="container my-3">

    {% if object_list %}
        <form method="GET" action="{% url 'movies:WatchListView' %}">

            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                    <label for="actor">Actor</label>
                    <input type="text" class="form-control" value="{{ request.GET.actor }}" name="actor"  id="actor" placeholder="Bradd Pit">
                </div>
                <div class="form-group col-md-4 mb-0">
                    <label for="genre">Genre</label>
                    <input type="text" value="{{ request.GET.genre }}" name="genre" class="form-control" id="genre" placeholder="Comedy">
                </div>
                <div class="form-group col-md-4 mb-0">
                    <label for="watched">Watched?</label>
                    <select name="watched" class="form-control" id="watched">
                    <option {% if request.GET.watched == "True" %}selected{% endif %} value="True">Yes</option>
                    <option {% if request.GET.watched == "False" %}selected{% endif %} value="False">No</option>
                    </select>
                </div>
            </div>
            <input type="submit" value="Filter" class="btn btn-secondary btn-block my-3">
        </form>
        <table class="table">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Movie Title</th>
            <th scope="col">Added</th>
            <th scope="col">Watched</th>
            </tr>
        </thead>
        <tbody>
        {% for movie in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ movie.movie_title }}
                    <form action="" class="d-inline ml-2" method="post">{% csrf_token %}
                        <a class="add-to-watchlist" movieId="{{ movie.movie_id }}" type="submit">
                            <i class="fas fa-file-video"></i>
                        </a>
                    </form>   
                </td>
                <td>{{ movie.added }}</td>
                <form method="POST" action="{% url 'movies:update_watchlist_item' movie.movie_id %}">{% csrf_token %}
                    <td>
                        <div class="input-group">
                            <select class="custom-select" name="watched">
                              <option {% if movie.watched %}selected{% endif %} value="True">True</option>
                              <option {% if not movie.watched %}selected{% endif %} value="False">False</option>
                            </select>
                        </div>
                    </td>
                    <td>
                        <input class="btn btn-success" type="submit" value="Update">
                    </td>
                </form>
                <td>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#detailModal{{ movie.pk }}">
                        Details
                    </button>
                </td>
            </tr>
            <!-- Modal -->
            <div class="modal fade" id="detailModal{{ movie.pk }}" tabindex="-1" role="dialog" aria-labelledby="detailModalTitle" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="detailModalTitle">Movie Details</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                    <h1>{{ movie.movie_title }}</h1>
                    <p>Actors:</p>
                    <p>{{ movie.movie_actors }}</p>
                    <p>Genre(s):</p>
                    <p>{{ movie.movie_genre }}</p>
                    <img src="{{ movie.movie_poster }}" alt="">
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}
        </tbody>
        </table>

    {% else %}
    <p>No movies added to watchlist yet. <a href="{% url 'movies:search_movies' %}">Add here.</a></p>
    {% endif %}

</div>

  

{% endblock content %}

{% block scripts %}
    <script src="{% static 'movies/js/movies.js' %}"></script>
{% endblock scripts %}

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
    <div class="container my-3">
        <div id="message">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button class="close" type="button" data-dismiss="alert"><span>&times;</span></button>
                {{ message|safe }}
            </div>
        </div>
    </div>

    {% endfor %}
{% endif %}

templates/partials/_card.html
{% load get_item %}

<div class="card mx-1 mb-2">

    <!-- Card content -->
    <div class="card-body"> 
        <form action="" class="d-inline float-right ml-2" method="post">{% csrf_token %}
            <a class="add-to-watchlist" movieId="{{ movie|get_item:'imdbID' }}" type="submit">
                <i class="fas fa-file-video"></i>
            </a>
        </form>                    
        <!-- Title -->
        <a href="">
            <p class="card-title font-weight-bold mb-0">{{ movie|get_item:'Title' }}</p>   
        </a>
                            
    </div>

    <!-- Card image -->
    <a href="">
        <img class="card-img-top rounded-0 img-fluid" src="{{ movie|get_item:'Poster' }}" alt="No image available">
    </a>


    <!-- Card content -->
    <small class="card-body">
        <div class="Stars" style="--rating: {{ recipe.get_average_rating|safe }}"><span class="d-none d-sm-inline" ><small class="text-muted">{{ recipe.ratings.get.count }}</small></span></div>
    </small>

</div>
<!-- Card -->

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item {% if request.path == '/' %}active{% endif %}">
        <a class="nav-link" href="{% url 'movies:search_movies' %}">Search movies</a>
      </li>
      <li class="nav-item {% if 'watchlist' in request.path %}active{% endif %}">
        <a class="nav-link" href="{% url 'movies:WatchListView' %}">Your watchlist</a>
      </li>
    </ul>
  </div>
</nav>

templates/partials/_pagination.html
{% with page=request.GET.page %}
<div class="row justify-content-center">
    <nav>
        <ul class="pagination flex-wrap">
          <li class="page-item {% if page|add:0 <= 1 or not page %}disabled{% endif %}"><a class="page-link" href="?title={{ request.GET.title }}&page={{ page|add:'-1' }}">Previous</a></li>

          {% for num in max_page %}
          <li class="page-item {% if num == page|add:0 or not page and num == 1 %}active{% endif %}"><a class="page-link" href="?title={{ request.GET.title }}&page={{ num }}">{{ num }}</a></li>
          {% endfor %}

          <li class="page-item {% if page|add:0 >= max_page|last %}disabled{% endif %}"><a class="page-link" href="?title={{ request.GET.title }}&page={% if page %}{{ page|add:'1' }}{% else %}2{% endif %}">Next</a></li>
        </ul>
      </nav>
</div>
{% endwith %}